### Generate a banner for a single page, overwriting any existing banner
POST http://localhost:3000/generate-banner
Content-Type: application/json

{
  "pageId": "7c07f96bb2ef42f7a72f5bed510806d4"
}

### Manually trigger banner generation for all pages, filtered out using notion-transformer.js::filterPage
POST http://localhost:3000/trigger-banner-generation
Content-Type: application/json

{}
